[project]
name = "codex_preprocessing"
version = "0.1"
requires-python = ">=3.10"

dependencies = [
    "numpy<2.0.0",
    "tqdm",
    "scipy",
    "hydra-core<=1.3.0",
    "hydra_colorlog",
    "pandas<=2.2.1",
    "matplotlib",
    "tensorflow==2.14.1",
    "scikit-learn",
    "tifffile<=2025.1.10",
    "scikit-image<=0.24.0",
    "PyWavelets",
    "openpyxl",
    "flowdec",
    "ashlar",
    "jax<=0.4.7",
    "jaxlib<=0.4.7",
    "hyperactive==4.4.0",
    "basicpy",
    "rich",
    "tabulate",
    "cucim-cu11",
    "cupy-cuda11x",
    "dask",
    "dask-image",
    "stackview",
    "opencv-python==4.10.0.82",

    # torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
    # lightning

    # "git+https://github.com/facebookresearch/detectron2.git",
    # "git+https://github.com/fbcotter/pytorch_wavelets",

    # pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/cu124

    # Compile Deformable-DETR CUDA operators
    # git clone https://github.com/fundamentalvision/Deformable-DETR.git
    # cd Deformable-DETR
    # cd ./models/ops
    # sh ./make.sh
]

[project.scripts]
codex_preprocess = "codex_preprocessing:main"
# codex_segment = "scripts.run_segmentation:main"

[tool.setuptools.packages]
find = { where = ["src", "."], include = ["codex_preprocessing*"] }

[build-system]
requires = ["setuptools>=67.8.0"]
build-backend = "setuptools.build_meta"

[tool.codespell]
skip = '.git,*.pdf,*.svg'
