[project]
name = "codex_preprocessing"
version = "0.1"
requires-python = ">=3.11"

dependencies = [
    # "tqdm",
    # "scipy",
    # "hydra-core",
    # "hydra_colorlog",
    # "pandas",
    # "matplotlib",
    # "tensorflow[and-cuda]",
    # # "cudnn",
    # "torch",
    # "torchvision",
    # "scikit-learn",
    # "tifffile<=2025.1.10",
    # "scikit-image<=0.24.0",
    # "PyWavelets",
    # "openpyxl",
    # "flowdec",
    # "ashlar",
    # "jax",
    # "jaxlib",
    # "hyperactive==4.4.0",
    # "pydantic<3.0.0",
    # "rich",
    # "tabulate",
    # "cucim-cu12",
    # "cupy-cuda12x",
    # "dask",
    # "dask-image",
    # "stackview",
    # "opencv-python-headless",
    # "sopa",
    # "cellpose",
    # "instanseg-torch",
    # "monai",

    # "git+https://github.com/facebookresearch/detectron2.git",
    # "git+https://github.com/fbcotter/pytorch_wavelets",

    # pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/cu124

    # Compile Deformable-DETR CUDA operators
    # git clone https://github.com/fundamentalvision/Deformable-DETR.git
    # cd Deformable-DETR
    # cd ./models/ops
    # sh ./make.sh
]

# [project.scripts]
# codex_preprocess = "main:main"
# codex_segment = "scripts.run_segmentation:main"

[tool.setuptools.packages]
find = { where = ["src", "."], include = ["codex_preprocessing*"] }

[build-system]
requires = ["setuptools>=67.8.0"]
build-backend = "setuptools.build_meta"

[tool.codespell]
skip = '.git,*.pdf,*.svg'
