#!/bin/bash
#SBATCH --partition=gn              
#SBATCH --gres=gpu:1                    
#SBATCH --job-name="prep_ipt"    
#SBATCH --output=./outputs/logs/BAT_WT.log  
#SBATCH --nodes=1                   
#SBATCH --ntasks=1                  
#SBATCH --cpus-per-task=16          
#SBATCH --mem=100G                  
#SBATCH --nodelist=gn03

python main.py +experiment=prep_BAT_WT
    # ~pipeline.deconvolution \
    # ~pipeline.edof \
    # ~pipeline.illumination_correction \
    # ~pipeline.stitching \
    # ~pipeline.background_correction  
    # ~pipeline.tma_dearray
