_target_: codex_preprocessing.modules.Basic
get_darkfield: true
smoothness_flatfield: 1.0
smoothness_darkfield: 1.0
sparse_cost_darkfield: 0.01
autosegment: false
autosegment_margin: 10
max_iterations: 500
max_reweight_iterations: 10
max_reweight_iterations_baseline: 5
rho: 1.5
mu_coef: 12.5
max_mu_coef: 1e7
optimization_tol: 1e-3
optimization_tol_diff: 1e-2
reweighting_tol: 0.01
sort_intensity: false
working_size: 128
